plugins { id 'com.android.application' }

android {
    namespace 'com.lucky.screenhang.v13'
    compileSdk 37

    defaultConfig {
        applicationId 'com.lucky.screenhang.v13'
        minSdk 29
        targetSdk 37
        versionCode 12
        versionName '1.4.2-exp'
    }

    buildFeatures { aidl true }
    buildTypes {
        debug {
            applicationIdSuffix '.test'
            versionNameSuffix '-test'
        }
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
